export const GATEWAY = [
  {
    id: "firstName",
    name: "firstName",
    label: "First Name",
    className: "select-button-2",
    type: "text",
    disabled: false,
    show: true,
  },
  {
    id: "lastName",
    name: "lastName",
    label: "Last Name",
    className: "select-button-2",
    type: "text",
    disabled: false,
    show: true,
  },
  {
    id: "index",
    name: "index",
    label: "Index",
    className: "select-button-2",
    type: "text",
    disabled: false,
    show: true,
  },
  {
    id: "phone",
    name: "phone",
    label: "Phone",
    className: "select-button-2",
    type: "number",
    disabled: false,
    show: true,
  },
  {
    id: "email",
    name: "email",
    label: "Email",
    className: "select-button-2",
    type: "email",
    disabled: false,
    show: true,
  },
  {
    id: "address",
    name: "address",
    label: "Address",
    className: "select-button-2",
    type: "text",
    disabled: false,
    show: true,
  },
];
